# Generated by Django 5.0.2 on 2025-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_wins', models.IntegerField(default=0)),
                ('user_losses', models.IntegerField(default=0)),
                ('user_draws', models.IntegerField(default=0)),
                ('computer_wins', models.IntegerField(default=0)),
                ('computer_losses', models.IntegerField(default=0)),
                ('computer_draws', models.IntegerField(default=0)),
            ],
        ),
    ]
